#pragma once

#define IDR_REVIVAL_HEADER 201
#define IDR_REVIVAL_LEGIT 202
#define IDR_REVIVAL_VISUALS 203
#define IDR_REVIVAL_MISC 204
#define IDR_REVIVAL_SCRIPTS 205
#define IDR_REVIVAL_THEMES 206
#define IDR_REVIVAL_CONFIGS 207
